### ISSUE TITLE
Oauth bridge

### ISSUE THREAD

**Issue by benjiqq** [CryptoverseCC/cryptoauth.io#1]
> 
> With Cryptoverse Auth you are able to do the same, the difference is that it validates that you are the owner of certain Ethereum address and tells the site that yes you really hold private keys to this address and that the site should use this address as your identity instead of your personal info.
> 
> You might ask how the site owner will reach you if the only information they receive is your Ethereum address? ETHMail to the rescue. By default Cryptoverse Auth passes your dedicated email address to the site your are login into. Those emails have a form of 0xYourAddress@ethmail.cc.
> 

I don't fully understand this. ethmail can be an oauth provider?

**Comment by gkapkowski** [comment]
ETHMail is using Cryptoverse Login (cryptoauth.io) as Identity Provider - You can think about it as Gmail (email service) with Google Account login (Google Is Identity provider for Gmail).

The second paragraph is a bit technical explanation. OpenID Connect can provide various information about given identity (name, surname, address, etc - the normal stuff), and it can provide email (eg. when you use google account login on some site the site can also receive your gmail email address during login), and by default Cryptoverse Login server passes ETHMail addresses in form 0xAddress@ethmail.cc during user login procedure.

**Comment by benjiqq** [comment]
"it's basically OpenID Connect (oAuth2 based) implementation that uses metamask/wallet to confirm identity."

What is teh role of metamask to confirm identity? What are the precise steps within the OpenID protocol? maybe some chart of the auth flow would be good to have.

**Comment by gkapkowski** [comment]
Metamask confirms ownership over given Ethereum address by signing unique message with its private key.

I think good place to start to understand OpenID Connect will be https://openid.net/connect/faq/ eg:
```
What problem does OpenID Connect solve?
It lets app and site developers authenticate users without taking on the responsibility of storing and managing passwords in the face of an Internet that is well-populated with people trying to compromise your users’ accounts for their own gain.
```
(Google login is OpenID Connect implementation, whenever you login to some google service or other website with "Login with Google account" you are using OpenID Connect protocol)

You can see simple diagrams of OpenID Connect at https://medium.com/@darutk/diagrams-of-all-the-openid-connect-flows-6968e3990660 (Most commonly used is `1. response_type=code` but others are also available with Cryptoauth)

I've also created more detailed diagram (it might be confusing if your are not familiar with oAuth2 information exchange)
(I did it from memory so it might contain some mistakes):
 
![Cryptoauth OpenID Connect Flow](https://user-images.githubusercontent.com/114996/86766287-9fd6f880-c04a-11ea-9957-9394ef63ad36.png)
Source (https://sequencediagram.org):
```
title Cryptoauth Authorization Flow (eg. community.cryptoverse.cc)

participant "Alice\n(human, sitting\nin front of\ncomputer)" as Alice
participant "Wallet\n(eg. metamask)" as wallet
participant "Web browser\n(eg. firefox)\n(a.k.a Client in OpenID spec)" as browser
participant "Website Backend\n(server)" as backend
participant "Cryptoauth Backend\n(server)" as ca_backend

Alice->browser:Clicks link to https://community.cryptoverse.cc
group #aaaaaa Browser loads https://community.cryptoverse.cc
browser<-->backend: Lots of HTTP traffic, HTML,CSS,JS etc.
end
Alice->browser:Moves mouse and clicks "Login with Ethereum Wallet"
group #aaffaa OpenID Connect plugin for Discourse
browser->backend:HTTP POST /auth/oidc 
note over backend:Cryptoverse community forum is using cryptoauth.io as\nIdentity Provider (through installed OpenID connect plugin)\nIt has **Client ID** and **Secret** required to communicate\nwith cryptoauth.io backend server
backend->browser:HTTP 302 Redirect:\nredirects to cryptoauth
end
browser->ca_backend: HTTP GET https://auth.cryptoverse.cc/oauth2/auth?client_id=community.cryptoverse.cc&....\n(Cryptoauth authorization endpoint)
ca_backend->browser: HTTP 200 Reponse: HTML+JS of Cryptoauth frontend code
box over browser: Loads cryptoauth HTML and JS, shows it to the user.\nIt displays login options provided by Cryptoauth
Alice->browser: Clicks "Using Ethereum Address"
group #99ff99 Cryptoauth Authorization (this is a simplification, exact flows have couple of additional elements)
box over browser: The JS code of Cryptoauth composes \na message to be signed by user using\nhis/her wallet.
note over browser: Unique message
browser->wallet: Web3WaletSignMessage("Unique message")
group #00aaff Alice signs message with her Wallet eg. Metamask
wallet-->Alice: Shows "sign this message" dialog
Alice-->wallet: Clicks "Yes/OK/Sign"
box over wallet: Signs message with **0x123** private key
end
wallet->browser: Signature
note over browser: Signature
browser->ca_backend: HTTP POST /... Signature
box over ca_backend: Verifies signature and \nextracts ethereum address:\nThe address is **0x123**
ca_backend->browser: HTTP 302 Redirect: Signature is **OK**, got to\n https://community.cryptoverse.cc/auth/oidc?code=SecretCode
browser->backend: HTTP POST /auth/oidc/?code=SecretCode
backend->ca_backend: HTTP POST /token [SecretCode + Authorization data]\nExchange SecretCode for identity information
ca_backend->backend: HTTP 200 Response: Identity confirmation\nAlice have ownership over 0x123 address\nHer email is 0x123@ethmail.cc
box over backend: Creates session cookie for Alice,\nstores Session ID and address **0x123** in database
backend->browser: HTTP 200 Respons + Session cookie
end
box over browser: Alice is logged in to https://community.cryptoverse.cc as **0x123**
```

**Comment by benjiqq** [comment]
I think there are several steps in proving ownership of names/identity and delegation of this. So in your diagram it would make sense to consider the high level steps and then break them down.

What about this e.g.: say instead of ENS we have something dedicated for managing user names. So instead of defaulting to pubkeys we assign a name. That name does not represent a domain to visit as in ENS, but a user. Similar to an email it's a name that does not necessary reflect a real name, but can be an alias. but it is humanly readable. So the high level step would be: 1) register "useralias" Alice123. 2) signin with useralias Alice123. 3) logged in with Alice123
